{% set name = "cgroupspy" %}
{% set version = "0.2.3" %}
{% set sha256 = "8ee941c7ab9234a0b17a81b0b26487f7f1031f78b7a24cdd8eed1b5fa5970496" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py==30,==31,==32,==33,==34,==35]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - cgroupspy
    - cgroupspy.contenttypes
    - cgroupspy.controllers
    - cgroupspy.interfaces
    - cgroupspy.nodes
    - cgroupspy.trees
    - cgroupspy.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cloudsigma/cgroupspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for managing cgroups
  description: |
    Python library for managing cgroups

    The library provides a pythonic way to manage and represent cgroups.
    It provides interfaces that convert python objects to cgroups
    compatible strings and vise versa.
  dev_url: https://github.com/cloudsigma/cgroupspy

extra:
  recipe-maintainers:
    - sodre
