travis:
  secure:
    BINSTAR_TOKEN: Z1Tdjhjqah/LyjxPnYWq7tjzGEjH057UgY7TfknhUz1pF1MmoBFhKwAi6O/7HRKg0SyU3F6q+v/JyQtCUM4qtBTujGRImTW35ZKuUva3zeFGA9c9GtxV9qz0tl8vULOev7DvDNHMxJjDMD3iZ04F5a7nRKbVw15gJWTTDlZ23ytNm1Zup0ifwk8yJq1vtkAxGsv4jUKWfoWYsULneMd5CzT9MrhEbQoE3hNTqfuofgbc8NSXOMIwsh1o2FiQVzhaMQBjF0FkIJi26YANn73mqmc+aOVsgRl3pLl1uBNCYJAw1qczIS3e9QLM11sQk1ZftFRocv5HlZCcgRLRdtnDimptEx3LsVyaheKV1pX76HTbF3hpVyL6G8X5DwFFzQZs57LFYCu+1MOJGBNRu6eMcZdecn/5DBMgsN3AqJYn6J96qGzkv0K2jc+JS7Q1WUVlsC7xPLb/LEc0eZwaWG4DVx6Z337mvi1+zIJN35vC+TjyUlYDyeptPyP6UeGnwC56MOhcGWTrxZGJ7HCNK4nkIEGBJe9xILpspDuKdRX65NuLlUQiHC4zlJIeHuLomwon1xHk8U0rexZr7TeocPyBuy/9+OjAgWjgrbHmDyHgry8j3L5wqBmZ6WiMvse6aWpbNB4HhySLQMNlG1/gQmPyZp6go32EOT9ClZgpH+J6sK0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
