travis:
  secure:
    BINSTAR_TOKEN: gQHCztcQLoYUhi4tr9d+BgXTxRy3w+z8Ejha6cUnJ/AaIqD+C3ZE0SHy/sGNJNaOJ4gIceZmYTHxM/uzlh1gvta0SZoBfNAEvQTtaxzukLjMcKvMSyYAPzvhLC4yXROJzBDp22dMaSaLrVeEtJBIx4GpdSzO1oBB1a05zK3l2B45u5Hv5PDLrZg5htVc6HT1tPEvk2vg1mh3qwgbDqvTh5m6705oJPPoMZnE6ytvOoETKhpWJQtKSGdWRXKjrY1S84h2nrY8S73g7kGP72TvmZBQgGZ5rA7nfh42bMzGPn6YtdhgmEUN17jEqPlsmt7RNlhQJCX26FWoY42d5B55HGX20z6tmjnGHJN4RNLvre6LCg+ypvH13WdT7Cf5syPXQIB2U2u/MsULufA1MbWx/q5KeNmhfhB0ZJ5sQixXnNBu9QBItQOMgoEgxLgS0/ath79EFcD7x0+rhDPfyaCsuxWUtQHCFJ9Yln0iy2bIov/slbRpKOuvuE0vIdvvVLqB3aDlyFMav7nzBnACNVW9sVx3lumOzTCEuTQ4qjcydDX3rP8fASwxPjHBruvdEGLrCGHZLp+m2AjxFt3q/Fnzaud1mS84FTzZQVcEqOtkqlwZunXrJF20hRZ3zgA152w8F18kRwOVdYEZa11/3UK79Hci6ycbl13jsUaLCxYTNIo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
