travis:
  secure:
    BINSTAR_TOKEN: u1BpO8hMPTm65qIA7zILj98sz1jfU1D5r7lvKf1tIFLQy65qTnznXIVOg/AkKEcbMeHH50TNfM9UrsFMvHOom4BMi5HNkjuQyPvM3agD12PuRkUBYVEkm5q+7Fjcwe3NxsYta0tLjoOcRDSl0wq0FnpC4HzJ/jiUnAhTnF+7f82ckS+jP5i4ZsDlVzOfWuj9IcxMwWB0LcrKUrds2VYkdWEV7B03FY2RrCowiOgXFwJZ2NaKLnbOZEOnXJnXja5PQ2v09iiKcmfw8m7zzvi4WrBgE65f1VJ035whPxDATZrHOFriEstmauNJkDdH/ycTFtQbUDe68Vhhdjbx6PAJrn6Z2UTf8J2WXosHBxXtQvepcCItigLZ9jUh+tBbqTanSefqOMto+u6e6ydrv4o3MXGM/vwz7SypqQ1PITh93sSQKcBqZvvPvQmypf0DyQ7fy5hZUdI1g6M0pkX95FvKPWjheJToETK1LQbcDNe1TVidsDDNOL9QPqg7PsXTt+ZbRiNu/jmDJ2a6evOUOb28hjryU425pHkBuYVnXdT0YUYDqNpKJ0noty3T10SpGfFjHtstQIu10spjg7YIccjqQdX8rRsDQloRt204jMXY6iKgYzbVsrB8iypmnQCMI74+6IEVvGQjbV78u0Ifi2jzznAt2xqQa3wTBwnK2szu/Ts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
