travis:
  secure:
    BINSTAR_TOKEN: jHZ5SIW/liXGbshbmzx/86oXZ9twAexvwcuLH0+W7cJByoaehTfDWqA1HOC9RLOtInOCFuBog0GSLm9GwTzL40SmZVu5LPuR0Icig4uTb3SEbsQmHZ+AZ3aIrDbc/GShNU3S90hOGzQ6dMFuWZ3KZ173F2815vW93I9m67buDysFIN9UxFM7rITZ+2nBGyI1nSf9nx3Jeu8AT35fF6HyI7CEhldngWiiukZmq9DmOtuqcniI+HT9P8PE7OmgSyPlIflLCaMJTsB8xI7L3tqOQxooeNNe3Yh1f+S0cH3+dDPfi6awh539TQgQUPQhg6fkNbQr2TfNnLL3vWg6OY8GNrJwQeVOtGdRRewBa8aq/PjU8rss8f+Qa7QXDhTLlyiOWL/r3egZzds+zpbHIfb9qpi7AvAZUXrrSsK5NTEJnfX9aYFeRxj8OG01xSIgxlcBpzW1lAxfQI6NitW7OJU0xAGNLel3KgJSD0p1VqAq91bnZ4JNUDrBNkGym24bPIXrU33MPs+G/S64oieDi/b88ujrJcNV4Z8rd8IT+5pFlrA6Wkk+oFfM0gTVjCD64FaBZ8yC+8x1eYDH7qlKBHnrHhcm/QzFH583M6FhPXqOmpLLbi9RcflHwarDl5mShQumQQmukB/C33zwOQB1AT8+njnL1iU7zsSIi+KCjuspVCE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
